pipeline {
  agent any

  //tools {
  // Install the Maven version configured as "M3" and add it to the path.
  // maven "M3"
  //}

  stages {
    stage('Create EC2 Instance'){
      steps {
        git 'https://github.com/swastiksuman/NodeZeroDeployPipeline.git'
        ansiblePlaybook installation: 'Ansible', playbook: 'playbooks/aws-create.yaml', extras: 'ansible_python_interpreter=/usr/bin/python3 aws_access_key=AKIAIQ2Q6VMEUYSRWUUQ aws_secret_key=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'
      }
    }
    stage('Build') {

      steps {
        // Get some code from a GitHub repository

      }

      post {
        // If Maven was able to run the tests, even if some of the test
        // failed, record the test results and archive the jar file.
        success {
          sh "echo Hello"
        }
      }
    }
  }
}
