---
  Resources:
    MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-08f3d892de259504d
        InstanceType: t2.micro
        KeyName: my-ubuntu
